spring:
  profiles:
    active: local

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true

  cloud:
    gcp:
      project-id: ${spring.cloud.gcp.project-id}
      storage:
        bucket:
          name: ${spring.cloud.gcp.storage.bucket.name}
        credentials:
          location: ${spring.cloud.gcp.storage.credentials.location}


swagger:
  server:
    local-url: ${swagger.server.local-url}
    prod-url: ${swagger.server.prod-url}

oauth:
  kakao:
    client-id: ${oauth.kakao.client-id}
    client-secret: ${oauth.kakao.client-secret}
    redirect-uri: ${oauth.kakao.redirect-uri}
    token-uri: ${oauth.kakao.token-uri}
    user-info-uri: ${oauth.kakao.user-info-uri}

jwt:
  secret: ${jwt.secret}
  expiry: ${jwt.expiry}

ai:
  server:
    url: ${ai.server.url}