name: Deploy to GCP App Engine

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build-and-deploy: # 잡 이름 변경
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout
      uses: actions/checkout@v3

    # 2. JDK 17 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. application.yml 파일 생성 (Secret 사용)
    - name: Set up application.yml
      run: |
        mkdir -p ./src/main/resources
        echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application-prod.yml
      shell: bash
      
    # 4. Gradlew 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 5. Gradle 빌드 (테스트 포함)
    - name: Build with Gradle
      run: ./gradlew clean build

    # 6. Google Cloud 인증 ★★★ 추가된 부분 ★★★
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # 7. App Engine에 배포 ★★★ 추가된 부분 ★★★
    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v2
      with:
        # GCP 프로젝트 ID를 GitHub Secret으로 등록하여 사용하는 것을 권장합니다.
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        
