name: Java CI with Gradle and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up application.yml for test
        run: |
          mkdir -p ./ie_um/src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./ie_um/src/main/resources/application.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./ie_um

      - name: Build with Gradle
        run: ./gradlew clean build
        working-directory: ./ie_um

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicdsample-jar
          path: ./ie_um/build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cicdsample-jar

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "*.jar"
          target: "~/cicd"
          script: |
            
            PID=$(lsof -t -i:8080)
            if [ -n "$PID" ]; then
              kill -9 $PID
            fi
            
            nohup java -jar -Dspring.profiles.active=prod ~/cicd/*.jar > ~/cicd/app.log 2>&1 &
